config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'homes/index'
  end
  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }
  
  devise_for :admin, skip: [:passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  namespace :public do
    get 'calendar/index'
    resources :sessions, only: [:new, :create, :destroy]
    resources :groups do
      get  'search',on: :collection
      resource :group_users, only: [:create, :destroy]
      resource :permits, only: [:create, :destroy, :show]
    end
  end

  
  scope module: :public do
    root 'homes#top'
    get 'about'=>"homes#about"
    get 'event_bookmarks/index'
    get 'event_bookmarks/show'
    get 'event_bookmarks/new'
    get 'event_bookmarks/edit'
    get 'photo_bookmarks/index'
    get 'photo_bookmarks/show'
    get 'photo_bookmarks/new'
    get 'photo_bookmarks/edit'
   
    resources :users do
      patch :withdrawal
    end
    resources :groups do
      resources :events
    end
    resources :events do
      resources :schedules
      resources :event_photos
    end
    
    resources :photos, only: [:index]
    end
  
   namespace :admin do
    resources :photos
    resources :users
    resources :groups
    get 'index', to: 'homes#index', as: 'top'
  end
    # events#index 
    get 'events', to: 'events#index', as: 'events_index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability


  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:email]        

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group
  has_many :schedules
  has_many :photos
  
  validates :title, presence: true
  validates :event_date, presence: true
            
  
 
  default_scope -> { order(start_time: :asc) }

#   validate  :start_end_check

   #時間の矛盾を防ぐ
#   def start_end_check
#      if self.start_time.present? && self.end_time.present?
#       errors.add(:end, "が開始時刻を上回っています。正しく記入してください。") if self.start > self.end 
#      end
#   end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :permits, dependent: :destroy
  has_many :users, through: :group_users
  belongs_to :owner, class_name: 'User'
  has_many :events
  has_many :photos, through: :events
  
 
  validates :name, presence: true, uniqueness: true
  validates :introduction, presence: true
  has_one_attached :group_image
  
  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
  
  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end
  def is_owned_by?(user)
    owner_id == user.id
  end
  
  def has_permits?(user)
    permits.exists?(user_id: user.id)
  end
  
  def self.search(method, word)
  # 完全に一致するnameを持つGroupを検索
  if method == "perfect_match"
    @groups = Group.where(name: word)
  else
  # エラーメッセージ出したい
  end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group
  
  validates :user_id, uniqueness: { scope: :group_id }
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_one_attached :image
  belongs_to :event
  has_one :group, through: :event
  has_many :users, through: :photo_bookmarks
end

app/models/photo_bookmark.rb
class PhotoBookmark < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :event
  
  validates :title, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_image
  has_many :permits, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users
  has_many :events, through: :groups
  has_many :photos, through: :events

  
  # バリテーション
  validates :name, uniqueness: true, presence: true, length: { minimum: 2, maximum: 15 }
  validates :introduction, length: { maximum: 50 }   
   
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
     profile_image.variant(resize_to_limit: [width, height]).processed
  end

GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  
  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/helpers/concern_helper.rb
module ConcernHelper
end

app/helpers/concerns_helper.rb
module ConcernsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<!--%- if devise_mapping.registerable? && controller_name != 'registrations' %>-->
<!--  %= link_to "Sign up", new_registration_path(resource_name) %><br />-->
<!--% end %>-->

<!--%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>-->
<!--  %= link_to "Forgot your password?", new_password_path(resource_name) %><br />-->
<!--% end %>-->

<!--%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>-->
<!--  %= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />-->
<!--< end %>-->

<!--%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>-->
<!--  %= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />-->
<!--< end %>-->

<!--<- if devise_mapping.omniauthable? %>-->
<!--  <- resource_class.omniauth_providers.each do |provider| %>-->
<!--    %= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />-->
<!--  < end %>-->
<!--<end %>-->

app/views/layouts/_footer.html.erb
<footer>
    <div class="pc">
    <%= image_tag  "logo.jpg",size:"155x45", class:"center"  %>  
    </div>
</footer>

<footer>
  <div class="su">
      <ul class="justify-content-center">
        <!--ログインしている時ユーザー-->
        <% if user_signed_in? %>
          <%= link_to root_path(current_user), class:"nav-link text-light" do %>
            <i class="fa-solid fa-house fa-2xl"></i>
          <%end%>
          <%= link_to public_calendar_index_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-calendar-days fa-2xl"></i>
          <% end %>
          <%= link_to groups_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-users fa-2xl"></i>
          <% end %>
          <%= link_to photos_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-images fa-2xl "></i>
          <% end %>
      <!--アドミンがログインしてる時 -->
        <% elsif admin_signed_in? %>
          <%= link_to admin_top_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-house fa-2xl"></i>
          <% end %>
       
          <%= link_to destroy_admin_session_path, method: :delete, class:"nav-link text-light" do %>
            <i class="fa-solid fa-right-from-bracket fa-2xl"></i>
          <% end %> 
          
          <!--ログインしていない時  -->
        <% else %>
          <%= link_to root_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-house fa-2xl"></i>
          <% end %>
          <%= link_to public_calendar_index_path, class:"nav-link text-light" do %>
            <i class="fa-regular fa-calendar-check fa-2xl"></i>
          <% end %>
          <%= link_to about_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-tag fa-2xl"></i>
          <% end %>
          <%= link_to new_user_session_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-right-to-bracket fa-2xl"></i>
          <% end %> 
        <% end %>
      </ul>
  </div>
</footer>
 

app/views/layouts/_header.html.erb
<div class="pc">
  <header>
    <li>
      <!-- アイコン -->
        <% if user_signed_in? %>
          <div>
            <%= link_to user_path(current_user) do %>
              <%= image_tag current_user.get_profile_image(60,60), class: "rounded-icon" %>
            <% end %>
          </div>
        <!--個人のアイコン-->
        <% else %>
        <div>
          <%= image_tag  "no_image.jpg", class: "rounded-icon",size:"60x60" %>
        </div>
        <% end %>
    
      <ul>
          <!-- ナビゲーションアイテム -->
        <!--ログインしている時ユーザー-->
        <% if user_signed_in? %>
          <%= link_to root_path(current_user), class:"nav-link text-light" do %>
            <i class="fa-solid fa-house fa-lg"></i>
          <% end %>
          <%= link_to public_calendar_index_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-calendar-days fa-lg"></i>
          <% end %>
          <%= link_to groups_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-users fa-lg"></i>
          <% end %>
          <%= link_to photos_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-images fa-lg "></i>
          <% end %>
      <!--アドミンがログインしてる時 -->
        <% elsif admin_signed_in? %>
          <%= link_to admin_top_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-house fa-lg"></i>
          <% end %>
        
          <%= link_to destroy_admin_session_path, method: :delete, class:"nav-link text-light" do %>
            <i class="fa-solid fa-right-from-bracket fa-lg"></i>
          <% end %> 
          
          <!--ログインしていない時  -->
        <% else %>
          <%= link_to root_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-house fa-lg"></i>
          <% end %>
          <%= link_to public_calendar_index_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-calendar-days fa-lg"></i>
          <% end %>
          <%= link_to about_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-tag fa-lg"></i>
          <% end %>
          <%= link_to new_user_session_path, class:"nav-link text-light" do %>
            <i class="fa-solid fa-right-to-bracket fa-lg"></i>
          <% end %> 
        <% end %>
      </ul>
    </li>
  </header>
</div>

<div class="su">
  <header>
    <ul>
      <!-- アイコン -->
        <% if user_signed_in? %>
          <div class="mr-auto">
            <%= link_to user_path(current_user) do %>
              <%= image_tag current_user.get_profile_image(40,40), class: "rounded-icon" %>
            <% end %>
          </div>
      
        <% else %>
          <%= image_tag  "no_image.jpg", class: "rounded-icon",size:"40x40" %>
        <% end %>
  
        <!--ロゴ  -->
        <%= image_tag  "logo.jpg",size:"145x40" , style:"margin: auto" %>  
   
    </ul>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PF</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!--FontAwesome-->
    <script src="https://kit.fontawesome.com/7c3c855863.js" crossorigin="anonymous"></script>
    <!--ブートストラップ-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    <!--fonnto-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Yomogi&display=swap" rel="stylesheet">
    
  </head>
    <body>
        <%= render 'layouts/header' %>
        <% if flash[:notice].present? %>
          <p><%= flash[:notice] %></p>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
    </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<!--カレンダー-->
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '◀︎'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= start_date.year %> <%= t('date.month_names')[start_date.month] %></span>
    <%= link_to t('simple_calendar.next', default: '▶︎'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>